Dir[File.expand_path('../ontraport/*.rb', __FILE__)].each do |file|
  require file
end

# @author Hamza Tayeb
# @see https://api.ontraport.com/doc ONTRAPORT API Documentation
module Ontraport
  BASE_URL = 'https://api.ontraport.com/'
  API_VERSION = '1'

  OBJECT_META = [
      {code: 0, name: :contact},
      {code: 1, name: :task},
      {code: 2, name: :staff},
      {code: 3, name: :group},
      {code: 4, name: :contact_log_entry},
      {code: 5, name: :sequence},
      {code: 6, name: :rule},
      {code: 7, name: :message},
      {code: 8, name: :subscriber},
      {code: 12, name: :note},
      {code: 13, name: :blast},
      {code: 14, name: :tag},
      {code: 16, name: :product},
      {code: 17, name: :purchase},
      {code: 19, name: :fulfillment},
      {code: 20, name: :landing_page},
      {code: 22, name: :smart_form},
      {code: 23, name: :queued_message},
      {code: 27, name: :pending_mail},
      {code: 30, name: :purchase_log},
      {code: 35, name: :affiliate_program},
      {code: 36, name: :affiliate},
      {code: 37, name: :affiliate_referral},
      {code: 38, name: :affiliate_commission},
      {code: 40, name: :promotion_item},
      {code: 75, name: :campaign},
  ]

  # Describe a given object type, including the numeric object Id and the available fields.
  #
  # @example
  #   Ontraport.describe :contact
  #
  # @param object [Symbol] the type of object you want to describe
  # @raise [ArgumentError] if the argument is not a +Symbol+
  # @raise [ObjectNotFoundError] if the argument does not match any object defined in the schema
  # @return [Hash{String=>String,Hash}] object metadata. Keys are:
  #   - +'name'+ - name of the object
  #   - +'fields'+ - Hash containing the object's fields
  #   - +'schema_object_id'+ - numeric Id of the object, as a String
  def self.describe object
    unless object.class.eql? Symbol
      raise ArgumentError.new "Must provide a symbol for the object name."
    end

    unless metadata = OBJECT_META.find{ |obj| obj[:name].eql? object }
      raise ObjectNotFoundError.new "No object matching #{object.inspect} could be found."
    end

    metadata
  end

  # Clear the cache of object metadata generated by the describe call. Use this
  # if you make changes to custom fields or objects in your ONTRAPORT instance and
  # don't want to reload the Ontraport module.
  # 
  # @example
  #   Ontraport.clear_describe_cache!
  #
  # @return [nil]
  def self.clear_describe_cache!
    @objects_meta_cache = nil
  end

  # @!group "Objects" Methods

  # Retrieve a single object of the specified type.
  # 
  # @example
  #   Ontraport.get_object :contact, 12345
  #   #=> #<Ontraport::Response @data=...>
  #
  # @param object_type [Symbol] the type of object, for instance +:contact+
  # @param id [Integer] Id of the record you want
  # @return [Response]
  def self.get_object object_type, id
    objects_call :get, object_type, endpoint: '/object', data: { id: id }
  end

  # Retrieve a collection of objects of the specified type, matching the query
  # specified by the parameters.
  #
  # @example
  #   Ontraport.get_objects :contact, { condition: "email like '%@foo.com'", sort: 'lastname' }
  #
  # @see https://api.ontraport.com/doc/#!/objects/getObjects List of accepted params
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] hash containing request parameters
  # @return [Response]
  def self.get_objects object_type, params={}
    objects_call :get, object_type, endpoint: '/objects', data: params
  end

  # Create an object with the given data
  #
  # @example
  #   Ontraport.create :contact, { email: 'foo@bar.com', firstname: 'Foo' }
  #   #=> #<Ontraport::Response @data=...>
  #
  # @see https://api.ontraport.com/doc/#!/objects/createObject API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] input data
  # @return [Response]
  def self.create object_type, params
    objects_call :post, object_type, endpoint: '/objects', data: params
  end

  # Create an object with the given data, or merge if the unique field matches another row.
  # 
  # @example
  #   Ontraport.save_or_update :contact, { email: 'foo@bar.com', firstname: 'Foo' }
  #   #=> #<Ontraport::Response @data=...>
  #
  # @see https://api.ontraport.com/doc/#!/objects/createormergeObject API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] input data
  # @return [Response]
  def self.save_or_update object_type, params
    objects_call :post, object_type, endpoint: '/objects/saveorupdate', data: params
  end

  # Given an object type, Id, and a +Hash+ of changes, update an single row.
  #
  # @example
  #   Ontraport.update_object :contact, 12345, { firstname: 'ChangeMe' }
  #   #=> #<Ontraport::Response @data=...>
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] update data. Use +.describe+ to get a list of available fields.
  # @return [Response]
  def self.update_object object_type, id, params
    objects_call :put, object_type, endpoint: '/objects', data: params.update(id: id)
  end

  # Add tags to objects matching the supplied conditions. In addition to various conditionals, you
  # may supply a list of Ids for objects you wish to tag (+ids+). The +add_list+ parameter (which contains the 
  # Ids of the tags you want to add) is required.
  #
  # @note The +add_list+ and +ids+ parameters should be strings comprised of comma-delimeted Integers.
  #
  # @example
  #   Ontraport.tag_objects :contact, { add_list: '11111,22222', ids: '33333,44444' }
  #   #=> #<Ontraport::Response @data=...>
  #
  # @see https://api.ontraport.com/doc/#!/objects/addTag API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] parameters describing the conditions of the tag operation.
  # @return [Response]
  def self.tag_objects object_type, params
    objects_call :put, object_type, endpoint: '/objects/tag', data: params
  end

  # Remove tags from objects matching the supplied conditions. Interface is nearly identical to +#tag_objects+
  #
  # @note This method expects +remove_list+ as a required parameter.
  #
  # @see tag_objects
  # @see https://api.ontraport.com/doc/#!/objects/removeTag API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] parameters describing the conditions of the tag operation.
  # @return [Response]
  def self.untag_objects object_type, params
    objects_call :delete, object_type, endpoint: '/objects/tag', data: params
  end

  # Add sequences to objects matching the supplied conditions. In addition to various conditionals, you
  # may supply a list of Ids for objects you wish to sequence (+ids+). The +add_list+ parameter (which contains the
  # Ids of the sequences you want to add) is required.
  #
  # @note The +add_list+ and +ids+ parameters should be strings comprised of comma-delimeted Integers.
  #
  # @example
  #   Ontraport.sequence_objects :contact, { add_list: '11111,22222', ids: '33333,44444' }
  #   #=> #<Ontraport::Response @data=...>
  #
  # @see https://api.ontraport.com/doc/#!/objects/addSequence API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] parameters describing the conditions of the sequence operation.
  # @return [Response]
  def self.sequence_objects object_type, params
    objects_call :put, object_type, endpoint: '/objects/sequence', data: params
  end

  # Add a campaign to objects matching the supplied conditions. In addition to various conditionals, you
  # may supply a list of Ids for objects you wish to sequence (+ids+). The +add_list+ parameter (which contains the
  # Ids of the campaigns you want to add/remove) is required.
  #
  # @note The +add_list+ and +ids+ parameters should be strings comprised of comma-delimeted Integers.
  #
  # @example
  #   Ontraport.campaign_objects :contact, { add_list: '11111,22222', ids: '33333,44444' }
  #   #=> #<Ontraport::Response @data=...>
  #
  # @see https://api.ontraport.com/doc/#subscribe-an-object-to-a-campaign-or-sequence API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] parameters describing the conditions of the sequence operation.
  # @return [Response]
  def self.campaign_objects object_type, params
    objects_call :put, object_type, endpoint: '/objects/subscribe', data: params.update(sub_type: 'Campaign')
  end

  # Remove a campaign to objects matching the supplied conditions. In addition to various conditionals, you
  # may supply a list of Ids for objects you wish to sequence (+ids+). The +remove_list+ parameter (which contains the
  # Ids of the campaigns you want to add/remove) is required.
  #
  # @note The +remove_list+ and +ids+ parameters should be strings comprised of comma-delimeted Integers.
  #
  # @example
  #   Ontraport.campaign_objects :contact, { add_list: '11111,22222', ids: '33333,44444' }
  #   #=> #<Ontraport::Response @data=...>
  #
  # @see https://api.ontraport.com/doc/#subscribe-an-object-to-a-campaign-or-sequence API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] parameters describing the conditions of the sequence operation.
  # @return [Response]
  def self.remove_campaign_objects object_type, params
    objects_call :delete, object_type, endpoint: '/objects/subscribe', data: params.update(sub_type: 'Campaign')
  end

  # Remove sequencess from objects matching the supplied conditions. Interface is nearly identical to +#sequence_objects+
  #
  # @note This method expects +remove_list+ as a required parameter.
  #
  # @see sequence_objects
  # @see https://api.ontraport.com/doc/#!/objects/removeSequence API docs
  #
  # @param object_type [Symbol] the type of object
  # @param params [Hash] parameters describing the conditions of the sequence operation.
  # @return [Response]
  def self.unsequence_objects object_type, params
    objects_call :delete, object_type, endpoint: '/objects/sequence', data: params
  end

  # @!endgroup
  # @!group "Transactions" Methods

  # Get full information about an order
  #
  # @see https://api.ontraport.com/doc/#!/transactions/getOrder API docs
  #
  # @param order_id [Integer] Id of the order
  # @return [Response]
  def self.get_order order_id
    request_with_authentication :get, endpoint: '/transaction/order', data: { id: order_id }
  end

  # @!endgroup

  private
    def self.request_with_authentication method, endpoint:, data: nil
      data_param = method.eql?(:get) ? :query : :body

      args = [method, "#{BASE_URL}#{API_VERSION}#{endpoint}"]
      kwargs = {
        :headers => { 'Api-Appid' => @configuration.api_id, 'Api-Key' => @configuration.api_key },
        data_param => data
      }

      response = HTTParty.send *args, **kwargs

      unless response.code.eql? 200
        error = "#{response.code} #{response.msg}"
        raise APIError.new(response.body.present? ? "#{error} - #{response.body}" : error)
      end

      Response.new **response.parsed_response.symbolize_keys
    end

    def self.objects_call method, object_type, endpoint:, data: {}
      metadata = describe object_type
      data.update 'objectID' => metadata[:code]

      request_with_authentication method, endpoint: endpoint, data: data
    end

    def self.objects_meta
      @objects_meta_cache ||= request_with_authentication :get, endpoint: '/objects/meta'
    end
end